### ISSUE TITLE
Issue with DB?

### ISSUE THREAD

**Issue by OhFenixHD** [Rubylium/DriftV#21] opened 2024-09-15 19:32 UTC
Hello im having issues witb db i think

Alr have same db on settings of server, on DB alr have all table created
Cannot create Crew and nothing
![image](https://github.com/user-attachments/assets/7f5991db-2242-440a-aaa7-56d725c0c250)

![image](https://github.com/user-attachments/assets/944938ab-d2bc-4afa-a827-dd20f8286abf)
![image](https://github.com/user-attachments/assets/c245a4c3-a49e-4671-8008-6e756b3d64e5)

**Comment by Rubylium** [comment] 2024-09-15 19:41
Did you import the sql script ? If not you need to:

```
-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               11.5.1-MariaDB-log - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Database structure for driftv
CREATE DATABASE IF NOT EXISTS `driftv` /*!40100 DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci */;
USE `driftv`;

-- Table structure for table `kvp`
CREATE TABLE IF NOT EXISTS `kvp` (
  `key` varchar(255) NOT NULL,
  `value` text DEFAULT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `players` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `license` VARCHAR(255) NOT NULL,
    `season` VARCHAR(255) NOT NULL,
    `pName` VARCHAR(255) NOT NULL,
    `money` INT NOT NULL DEFAULT 0,
    `driftPoint` INT NOT NULL DEFAULT 0,
    `exp` INT NOT NULL DEFAULT 0,
    `level` INT NOT NULL DEFAULT 0,
    `cars` JSON NOT NULL,
    `succes` JSON NOT NULL,
    `crew` VARCHAR(255) NOT NULL DEFAULT 'None',
    `crewOwner` BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (`license`, `season`)
);

CREATE TABLE `crews` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `tag` VARCHAR(255) NOT NULL,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `memberCount` INT NOT NULL DEFAULT 1,
    `totalPoints` INT NOT NULL DEFAULT 0,
    `win` INT NOT NULL DEFAULT 0,
    `loose` INT NOT NULL DEFAULT 0,
    `elo` INT NOT NULL DEFAULT 1000,
    `members` JSON NOT NULL,
    `rank` INT NOT NULL DEFAULT 500
);

-- Exported data was not selected.

-- Restore previous settings
/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
```

**Comment by Rubylium** [comment] 2024-09-15 19:41
And when it is done, change your database name to "driftv" instead of the zap code you have

**Comment by OhFenixHD** [comment] 2024-09-15 19:42
cant import with those part

CREATE DATABASE IF NOT EXISTS `driftv` /*!40100 DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci */;
USE `driftv`;

**Comment by Rubylium** [comment] 2024-09-15 19:42
> cant import with those part
> 
> CREATE DATABASE IF NOT EXISTS `driftv` /*!40100 DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci */; USE `driftv`;

What error do you have ?

**Comment by OhFenixHD** [comment] 2024-09-15 19:43
#1044 - Acceso negado para usuario: 'zap425478-6'@'%' para la base de datos 'driftv'

![image](https://github.com/user-attachments/assets/e3442e4f-b739-4453-a94b-119fe032091b)

**Comment by Rubylium** [comment] 2024-09-15 19:44
It seems you don't have permission to import the database ? Not sure how zap handle this, but the issue is not with the import script :/

**Comment by OhFenixHD** [comment] 2024-09-15 19:45
if put zap db name, import all without issue, for those i saying, if can redirect script to that?

**Comment by Rubylium** [comment] 2024-09-15 19:46
Yeah but that mean the db will not be created with the correct name, so the code will not be able to acces it correctly :/

**Comment by OhFenixHD** [comment] 2024-09-15 19:49
hmm, cant manually change on scripts maybe?

No have permission to rename/create with other names

**Comment by Rubylium** [comment] 2024-09-15 19:53
Umh yes you could edit the files, but that would be a bit annoying for futur updates. Give me 15-30min, I will code an update that add an option for custom database name in the config

**Comment by OhFenixHD** [comment] 2024-09-15 19:54
alr tysm <33

**Comment by Rubylium** [comment] 2024-09-15 20:03
After reading my code again it shouldn't cause issue. Can you try adding the database with the zap name and tell me if there is errors with that ? Also in the server cfg make sure it's oxmysql and not mysql-async loaded ( I updated the readme about it )

**Comment by OhFenixHD** [comment] 2024-09-15 20:11
Hi, with the oxmysql it works perfect <3

Alr have money working, drift give money, can create crew, etc...

ty for fix <3

**Comment by Rubylium** [comment] 2024-09-15 20:12
Alright great! Closing this issue then :)

**Closed as completed by Rubylium** 2024-09-15 20:12 UTC
Labels: question
